import { GateType, Challenge } from './types';

export const GATE_CONFIGS: Record<GateType, { inputs: number; color: string; description: string }> = {
  AND: { inputs: 2, color: 'bg-[#FF6B6B]', description: 'Needs BOTH inputs to be happy! 🤝' },
  OR: { inputs: 2, color: 'bg-[#4ECDC4]', description: 'Happy if EITHER input is on! 🌈' },
  NOT: { inputs: 1, color: 'bg-[#FFE66D]', description: 'Does the opposite of what you say! 🙃' },
  NAND: { inputs: 2, color: 'bg-[#95E1D3]', description: 'The opposite of AND. Very picky! 🙅‍♂️' },
  NOR: { inputs: 2, color: 'bg-[#F38181]', description: 'The opposite of OR. Loves quiet! 🤫' },
  XOR: { inputs: 2, color: 'bg-[#A8D8EA]', description: 'Only happy if inputs are different! 🎭' },
};

export const CHALLENGES: Challenge[] = [
  {
    id: '1',
    title: '🌟 The Magic AND Gate',
    description: 'The AND gate is like a best friend! It only turns on the light when BOTH switches are ON. Can you make the bulb glow?',
    difficulty: 'Easy',
    targetTruthTable: [
      { inputs: [false, false], output: false },
      { inputs: [true, false], output: false },
      { inputs: [false, true], output: false },
      { inputs: [true, true], output: true },
    ],
    solution: 'Place an AND gate. Connect Switch 1 to the top input and Switch 2 to the bottom input. Then connect the gate output to the bulb!',
  },
  {
    id: '2',
    title: '🌈 The Happy OR Gate',
    description: 'The OR gate is very easy to please! It turns on the light if Switch 1 OR Switch 2 (or both!) is ON.',
    difficulty: 'Easy',
    targetTruthTable: [
      { inputs: [false, false], output: false },
      { inputs: [true, false], output: true },
      { inputs: [false, true], output: true },
      { inputs: [true, true], output: true },
    ],
    solution: 'Place an OR gate. Connect Switch 1 and Switch 2 to its inputs, and connect the output to the bulb.',
  },
  {
    id: '3',
    title: '🙃 The Silly NOT Gate',
    description: 'The NOT gate loves to do the opposite! If the switch is OFF, the light is ON. If the switch is ON, the light is OFF!',
    difficulty: 'Easy',
    targetTruthTable: [
      { inputs: [false], output: true },
      { inputs: [true], output: false },
    ],
    solution: 'Place a NOT gate. Connect Switch 1 to its input, and connect the output to the bulb.',
  },
  {
    id: '4',
    title: '🚀 Double Power!',
    description: 'Can you use TWO AND gates to make a light turn on only when THREE switches are all ON?',
    difficulty: 'Medium',
    targetTruthTable: [
      { inputs: [false, false, false], output: false },
      { inputs: [true, true, false], output: false },
      { inputs: [true, true, true], output: true },
    ],
    solution: 'Use two AND gates. Connect Switch 1 and Switch 2 to the first gate. Then connect the output of the first gate and Switch 3 to the second gate. Finally, connect the second gate to the bulb!',
  },
  {
    id: '5',
    title: '🎈 Either One works',
    description: 'Use an OR gate and a NOT gate to make the light turn ON when the switch is OFF.',
    difficulty: 'Medium',
    targetTruthTable: [
      { inputs: [false], output: true },
      { inputs: [true], output: false },
    ],
    solution: 'Connect Switch 1 to a NOT gate, then connect the NOT gate output to the bulb. (The OR gate isn\'t actually needed for this simple version, but you could put it after the NOT gate!)',
  },
  {
    id: '6',
    title: '🎭 The Secret XOR',
    description: 'This is a tricky one! The light only turns on if EXACTLY one switch is ON. If both are ON, they cancel each other out!',
    difficulty: 'Hard',
    targetTruthTable: [
      { inputs: [false, false], output: false },
      { inputs: [true, false], output: true },
      { inputs: [false, true], output: true },
      { inputs: [true, true], output: false },
    ],
    solution: 'Just use one XOR gate! Connect Switch 1 and Switch 2 to its inputs, and connect the output to the bulb.',
  },
  {
    id: '7',
    title: '🏛️ The Majority Rules',
    description: 'In this game, the majority wins! With 3 switches, the light turns ON only if TWO or THREE switches are turned ON.',
    difficulty: 'Hard',
    targetTruthTable: [
      { inputs: [false, false, false], output: false },
      { inputs: [true, false, false], output: false },
      { inputs: [false, true, false], output: false },
      { inputs: [false, false, true], output: false },
      { inputs: [true, true, false], output: true },
      { inputs: [true, false, true], output: true },
      { inputs: [false, true, true], output: true },
      { inputs: [true, true, true], output: true },
    ],
    solution: 'You need to check all pairs: (S1 AND S2) OR (S1 AND S3) OR (S2 AND S3). Use three AND gates for the pairs and two OR gates to combine them!',
  },
  {
    id: '8',
    title: '🤖 The Robot\'s Choice',
    description: 'Switch 1 is the Boss! If the Boss is ON, the light follows Switch 2. If the Boss is OFF, the light follows Switch 3. Can you build this "Selector"?',
    difficulty: 'Hard',
    targetTruthTable: [
      { inputs: [false, false, false], output: false },
      { inputs: [false, true, false], output: false },
      { inputs: [false, false, true], output: true },
      { inputs: [false, true, true], output: true },
      { inputs: [true, false, false], output: false },
      { inputs: [true, true, false], output: true },
      { inputs: [true, false, true], output: false },
      { inputs: [true, true, true], output: true },
    ],
    solution: 'This is a Multiplexer! Use (S1 AND S2) OR ((NOT S1) AND S3). You will need two AND gates, one NOT gate, and one OR gate.',
  },
  {
    id: '9',
    title: '🏰 The Castle Gate',
    description: 'The castle gate only opens if the King (S1) says YES, or if BOTH Guards (S2 and S3) agree! Can you protect the castle?',
    difficulty: 'Hard',
    targetTruthTable: [
      { inputs: [false, false, false], output: false },
      { inputs: [false, true, false], output: false },
      { inputs: [false, false, true], output: false },
      { inputs: [false, true, true], output: true },
      { inputs: [true, false, false], output: true },
      { inputs: [true, true, false], output: true },
      { inputs: [true, false, true], output: true },
      { inputs: [true, true, true], output: true },
    ],
    solution: 'Use an AND gate for the Guards (S2 AND S3). Then use an OR gate to combine the King (S1) with the Guards\' result: S1 OR (S2 AND S3).',
  },
];
